### ISSUE TITLE
Increase the size of sifname in the decoder

### ISSUE THREAD

**Issue by amontoison** [ralna/SIFDecode#17]
@nimgould 
```shell
./sifdecoder_standalone home/alexis/.julia/artifacts/ffce006f880f075a016518c0de48131b983731d4/bin/AKIVA.SIF
 SIF file home/alexis/.julia/a does not exist
```
Is it fine to increase the length [here](https://github.com/ralna/SIFDecode/blob/master/src/decode/sifdecoder_standalone_main.f90#L46)?

Update: it seems to work if I increase the size!

**Comment by amontoison** [comment]
Another remark, is it normal that an `AUTOMAT.d` is not always generated?

**Comment by amontoison** [comment]
I algo got this error when I tried to decoded `AKIVA` with a parameter:
```
 Unrecognised command line argument: -paramM=5
```
Same error with `-param,M=5`.

**Comment by amontoison** [comment]
```julia
julia> CUTEst.sifdecoder("AKIVA", precision=:single)

EXTER_s.f:104:37:

  104 |       PARAMETER (ZERO = 0.0 , GRAND = 1.0D308)
      |                                     1
Error: Arithmetic overflow converting REAL(8) to REAL(4) at (1). This check can be disabled with the option ‘-fno-range-check’
EXTER_s.f:431:36:

  431 |             DO 1200 NOEUD = 1,NNOEUE-1
      |                                    1
Error: Symbol ‘nnoeue’ at (1) has no IMPLICIT type; did you mean ‘nnoeud’?
ERROR: failed process: Process(`gfortran -c -fPIC EXTER_s.f`, ProcessExited(1)) [1]
```

**Comment by amontoison** [comment]
Is it also possible to support the option `-dp` (like `-sp` and `-qp`) even if it's a no-op argument?
From Julia, it's easier to provide `-dp` than nothing if we handle multiple precision.

**Comment by nimgould** [comment]
> I algo got this error when I tried to decoded `AKIVA` with a parameter:
> 
> ```
>  Unrecognised command line argument: -paramM=5
> ```
> 
> Same error with `-param,M=5`.
 There has to be a space between keywords and values (that is what the 
fortran intrinsics rely on)

**Comment by nimgould** [comment]
> Is it also possible to support the option `-dp` (like `-sp` and `-qp`) even if it's a no-op argument? From Julia, it's easier to provide `-dp` than nothing if we handle multiple precision.

No problem, I'll add it
