### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by amontoison** [ralna/SIFDecode#18]
@jfowkes 
We should add a README.md like we did for GALAHAD.

It can be short but it should contains these information:
- How to compile SIFDecode with Meson (or ARCHDefs)
- What is the binary (or bash script) to decode SIF files
- Add a few examples with various options (like precision)

**Comment by nimgould** [comment]
I tried to make a new 2.5.1 release, but clearly you are using something else, and the latest release  has stayed at 2.5.0. What do I need to do? The CUTEst tests are failing as they are still using the old (buggy) sifdecoder

**Comment by amontoison** [comment]
You need to do like GALAHAD and CUTEst:
```shell
git checkout master
git tag v2.5.1
git push --tags
```
GitHub will create a release with precompiled binaries automatically for us.

**Comment by nimgould** [comment]
Thank you, I forgot!
