### ISSUE TITLE
Provide the list of problems that can be only decoded in double precision

### ISSUE THREAD

**Issue by amontoison** [ralna/SIFDecode#23]
Because of the file `EXTER.f`, we can't decode 33 problems in single / quadruple precision.
see https://github.com/ralna/SIFDecode/pull/20#issuecomment-2293442685

cc @jfowkes

**Comment by amontoison** [comment]
The problems that can't be decoded in single precision:
- HIELOW.SIF
- HS68.SIF
- HS69.SIF
- PARKCH.SIF
- STRATEC.SIF

The problems that can't be decoded in quaduple precision:
- AKIVA.SIF
- BLEACHNG.SIF
- CAR2.SIF
- HIELOW.SIF
- HS88.SIF
- HS89.SIF
- HS90.SIF
- HS91.SIF
- HS92.SIF
- JIMACK.SIF
- ORBIT2.SIF
- PARKCH.SIF
- RAYBENDS.SIF
- SARO.SIF
- SAROMM.SIF
- STRATEC.SIF

**Comment by nimgould** [comment]
Hilow, packh and stratec are variants of  akiva, that we fixed, so those are easy. I'll look at hs68/9 tomorrow

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nimgould** [comment]
I modified the decoder and SIF files so that these should now work. Please try again

**Comment by amontoison** [comment]
All tests have now passed with the new SIF files and decoder.
Great job, Nick!
