### ISSUE TITLE
Meson does not install sifdecoder bash script

### ISSUE THREAD

**Issue by jfowkes** [ralna/SIFDecode#29]
@amontoison for backwards compatibility we really should let meson install the old `sifdecoder` bash script.

**Comment by amontoison** [comment]
@jfowkes Do you that by defaut or only if an option is set to `true`?
We just need to copy the bash script so not a lot of work :)

**Comment by nimgould** [comment]
Definitely by default. For people who are using sifdec/cutest for all of the other supported
third-party packages that cutest interfaces to, this is vital

**Comment by amontoison** [comment]
It's the end of the day for me on this side of the Earth, but I can do it before the end of the week.

**Comment by nimgould** [comment]
No, not urgent as presumably the old (makefile) install still works.

Be careful, there is a gravitational singularity as you move from our side to yours via the edge

**Comment by amontoison** [comment]
Jari, the release 2.6.2 of `SIFDecode` also installs the shell script `sifdecoder` now.

**Comment by jfowkes** [comment]
Amazing thank you!
